<?php

return [
    'enabled' => env('APP_ENV') !== 'testing'
        && filter_var(
            env('HEALTH_DATA_ENCRYPTION_ENABLED', false),
            FILTER_VALIDATE_BOOLEAN
        ),

    // Keep identity/search columns plain so admin lookup remains indexable.
    'fields' => [
        'health_profiles' => [
            'home_address' => 'home_address_encrypted',
            'street' => 'street_encrypted',
            'barangay' => 'barangay_encrypted',
            'municipality' => 'municipality_encrypted',
            'province' => 'province_encrypted',
            'zipcode' => 'zipcode_encrypted',
            'birthday' => 'birthday_encrypted',
            'age' => 'age_encrypted',
            'sex' => 'sex_encrypted',
            'civil_status' => 'civil_status_encrypted',
            'height' => 'height_encrypted',
            'weight' => 'weight_encrypted',
            'blood_type' => 'blood_type_encrypted',
            'guardian_name' => 'guardian_name_encrypted',
            'landline' => 'landline_encrypted',
            'cellphone' => 'cellphone_encrypted',
            'medical_history' => 'medical_history_encrypted',
            'other_illness' => 'other_illness_encrypted',
            'food_allergies' => 'food_allergies_encrypted',
            'no_allergies' => 'no_allergies_encrypted',
            'medicine_allergies' => 'medicine_allergies_encrypted',
            'other_med_allergies' => 'other_med_allergies_encrypted',
            'has_disability' => 'has_disability_encrypted',
            'disability_type' => 'disability_type_encrypted',
            'has_illness' => 'has_illness_encrypted',
            'xray_date' => 'xray_date_encrypted',
            'xray_findings' => 'xray_findings_encrypted',
            'xray_findings_details' => 'xray_findings_details_encrypted',
            'doctor_name' => 'doctor_name_encrypted',
            'med_cert_date' => 'med_cert_date_encrypted',
            'med_cert_findings' => 'med_cert_findings_encrypted',
            'med_cert_findings_details' => 'med_cert_findings_details_encrypted',
            'is_smoker' => 'is_smoker_encrypted',
            'is_drinker' => 'is_drinker_encrypted',
            'covid_vaccinated' => 'covid_vaccinated_encrypted',
            'vaccine_history' => 'vaccine_history_encrypted',
            'blood_pressure' => 'blood_pressure_encrypted',
            'pulse_rate' => 'pulse_rate_encrypted',
            'respiratory_rate' => 'respiratory_rate_encrypted',
            'temperature' => 'temperature_encrypted',
            'covid_positive' => 'covid_positive_encrypted',
            'covid_positive_date' => 'covid_positive_date_encrypted',
            'medical_condition_remarks' => 'medical_condition_remarks_encrypted',
            'assessment_remarks' => 'assessment_remarks_encrypted',
            'med_assessment_remarks' => 'med_assessment_remarks_encrypted',
            'pending_reason' => 'pending_reason_encrypted',
            'encode_remarks' => 'encode_remarks_encrypted',
            'health_declaration' => 'health_declaration_encrypted',
            'medical_certificate_issued_by' => 'medical_certificate_issued_by_encrypted',
            'medical_certificate_issued_at' => 'medical_certificate_issued_at_encrypted',
            'chest_xray_result_text' => 'chest_xray_result_text_encrypted',
            'chest_xray_date' => 'chest_xray_date_encrypted',
            'assessment_date' => 'assessment_date_encrypted',
            'final_review_draft_data' => 'final_review_draft_data_encrypted',
        ],
        'health_profile_emp' => [
            'home_address' => 'home_address_encrypted',
            'street' => 'street_encrypted',
            'barangay' => 'barangay_encrypted',
            'municipality' => 'municipality_encrypted',
            'province' => 'province_encrypted',
            'contact_no' => 'contact_no_encrypted',
            'emergency_contact_person' => 'emergency_contact_person_encrypted',
            'emergency_contact_no' => 'emergency_contact_no_encrypted',
            'form_date' => 'form_date_encrypted',
            'age' => 'age_encrypted',
            'sex' => 'sex_encrypted',
            'civil_status' => 'civil_status_encrypted',
            'birthday' => 'birthday_encrypted',
            'past_medical_history' => 'past_medical_history_encrypted',
            'past_medical_history_others' => 'past_medical_history_others_encrypted',
            'previous_hospitalization' => 'previous_hospitalization_encrypted',
            'previous_hospitalization_details' => 'previous_hospitalization_details_encrypted',
            'operation_surgery' => 'operation_surgery_encrypted',
            'operation_surgery_details' => 'operation_surgery_details_encrypted',
            'current_medications' => 'current_medications_encrypted',
            'allergies' => 'allergies_encrypted',
            'family_history' => 'family_history_encrypted',
            'family_history_others' => 'family_history_others_encrypted',
            'cigarette_smoking' => 'cigarette_smoking_encrypted',
            'alcohol_drinking' => 'alcohol_drinking_encrypted',
            'traveled_abroad' => 'traveled_abroad_encrypted',
            'has_disability' => 'has_disability_encrypted',
            'disability_type' => 'disability_type_encrypted',
            'vital_signs_distress_status' => 'vital_signs_distress_status_encrypted',
            'height' => 'height_encrypted',
            'weight' => 'weight_encrypted',
            'bmi' => 'bmi_encrypted',
            'bp' => 'bp_encrypted',
            'hr' => 'hr_encrypted',
            'rr' => 'rr_encrypted',
            'temperature' => 'temperature_encrypted',
            'head_findings' => 'head_findings_encrypted',
            'eyes_findings' => 'eyes_findings_encrypted',
            'ears_findings' => 'ears_findings_encrypted',
            'throat_findings' => 'throat_findings_encrypted',
            'chest_lungs_findings' => 'chest_lungs_findings_encrypted',
            'chest_xray_result' => 'chest_xray_result_encrypted',
            'breast_findings' => 'breast_findings_encrypted',
            'heart_murmur' => 'heart_murmur_encrypted',
            'heart_rhythm' => 'heart_rhythm_encrypted',
            'abdomen_findings' => 'abdomen_findings_encrypted',
            'genito_urinary_date_lmp' => 'genito_urinary_date_lmp_encrypted',
            'extremities_findings' => 'extremities_findings_encrypted',
            'vertebral_column_findings' => 'vertebral_column_findings_encrypted',
            'skin_findings' => 'skin_findings_encrypted',
            'scars_findings' => 'scars_findings_encrypted',
            'working_impression' => 'working_impression_encrypted',
            'for_work_up' => 'for_work_up_encrypted',
            'referred_to' => 'referred_to_encrypted',
            'referred_to_others' => 'referred_to_others_encrypted',
            'follow_up_on' => 'follow_up_on_encrypted',
            'fit_status' => 'fit_status_encrypted',
            'health_declaration' => 'health_declaration_encrypted',
            'draft_data' => 'draft_data_encrypted',
        ],
        'dependents_profiles' => [
            'birthday' => 'birthday_encrypted',
            'age' => 'age_encrypted',
            'sex' => 'sex_encrypted',
            'civil_status' => 'civil_status_encrypted',
            'street' => 'street_encrypted',
            'barangay' => 'barangay_encrypted',
            'municipality' => 'municipality_encrypted',
            'province' => 'province_encrypted',
            'home_address' => 'home_address_encrypted',
            'contact_no' => 'contact_no_encrypted',
            'landline' => 'landline_encrypted',
            'emergency_contact_name' => 'emergency_contact_name_encrypted',
            'emergency_contact_no' => 'emergency_contact_no_encrypted',
        ],
        'health_form_submissions' => [
            'profile_snapshot' => 'profile_snapshot_encrypted',
            'remarks' => 'remarks_encrypted',
        ],
    ],
];
